### ISSUE TITLE
Warn users that PostgreSQL should not be exposed to Internet

### ISSUE THREAD

**Issue by yanokwa** [getodk/docs#1037]
See https://forum.opendatakit.org/t/aggregate-data-loss-on-digital-ocean-droplet/19940 for the post that inspired this issue. In lieu of the warning, we can also try auto-generating a secure password for the PostgreSQL DB. What do you think, @ggalmazor?

Related: https://forum.opendatakit.org/t/change-the-password-aggregate-uses-to-connect-to-postgres/19770

**Comment by scampus77** [comment]
Hi, as @ggalmazor suggested, below you can read the DigitalOcean team reply concerning the topic on https://forum.opendatakit.org/t/aggregate-data-loss-on-digital-ocean-droplet/19940
Thanks  

> Hey there,
> Unfortunately there isn't much we can do to directly recover the data removed by the attacker; I personally recommend against paying any kind of fee to get it back as the attacker often times simply won't restore anything after being paid.
> 
> If you have an external backup I recommend utilizing that to restore any data possible.
> With regards to security for the future to help avoid this type of issue you can check out Postgres documentation here: https://www.postgresql.org/docs/7.0/security.htm and this blog post here which I found nice looking: https://severalnines.com/blog/how-secure-your-postgresql-database-10-tips (this is a 3rd party blog post, I haven't run through everything so take it with a grain of salt).

> I wish there was more we could do in this instance to help you restore this data; the above should help avoid future situations like this.
> 
> You could instead look into utilizing our Managed Database service with Postgres as your DB Engine. We offer some cool security features by default like "Trusted Sources" which can limit access to your cluster to specific IPs/resources on DO: https://www.digitalocean.com/docs/databases/how-to/clusters/secure-clusters/
> 
> If you have any other questions or need anything else, just write back in and let us know! Thank you for being a DigitalOcean customer, we are here to assist you
> Regards
