### ISSUE TITLE
Add more precision to make Enpoint running over HTTPS

### ISSUE THREAD

**Issue by benfelt** [getodk/docs#1180]
An instruction is missing to help people to make ODK EndPoint running over HTTPS. 

On the https://docs.opendatakit.org/odk-x/sync-endpoint page, in the HTTPS paragraph I would add that one must edit the docker-compose.yml file and change the value of file : com.nginx.sync-endpoint.conf to ./config/nginx/sync-endpoint-http**s**.conf

Hope this helps

**Comment by yanokwa** [comment]
Closing in favor of https://github.com/odk-x/docs/issues/25
