### ISSUE TITLE
Document defaults for images

### ISSUE THREAD

**Issue by lognaturel** [getodk/docs#1184]
We may want to wait for https://github.com/XLSForm/pyxform/issues/405

https://github.com/opendatakit/collect/pull/3579

**Comment by lognaturel** [comment]
If an image default is set, it's possible to require that it get changed by adding a constraint that checks that the node value has changed. Something like `not(${my_image} = 'jr://images/my_image_default.png')`.

**Comment by seadowg** [comment]
As far as I can see the `audio` qustion doesn't support defaults in Collect. Good to add notes around that as well.
