### ISSUE TITLE
Doc link to OI File Manager is broken

### ISSUE THREAD

**Issue by SteveALee** [getodk/docs#1215]
On page https://docs.opendatakit.org/odk-x/survey-install/

the following link is 404

```
As well as the following third party apps:

        OI File Manager
```

Why is this app needed?

**Comment by lognaturel** [comment]
ODK-X now has its own documentation at https://docs.odk-x.org/! You can find the repository at https://github.com/odk-x/docs. It looks like this issue was addressed by https://github.com/odk-x/docs/pull/11.
