### ISSUE TITLE
Couldn't find the repository for Javarosa docs. 

### ISSUE THREAD

**Issue by ChakshuGautam** [getodk/docs#1220]
I was planning to dive deeper into how Javaroda works but couldn't find any documentation on the same. The old bitbucket repository is not functional and would be glad if you can point me to the starting point. [This](https://github.com/getodk/docs/blob/master/odk1-src/javarosa.rst) doc didn't help much.

**Comment by lognaturel** [comment]
Hello @ChakshuGautam! JavaRosa is maintained at https://github.com/getodk/javarosa. It has minimal inline documentation. If you're interested in contributing to its development, consider joining the #javarosa-code channel in [Slack](https://slack.getodk.org) and asking some questions there.

**Comment by ChakshuGautam** [comment]
@lognaturel Thanks for the prompt reply. Sorry to bug you again, but I am not able to join the channel. It says `token_revoked` when trying to get an invite. Who should I contact regarding this?

**Comment by lognaturel** [comment]
Ah, I now see that was discussed earlier today. Whoops. [Here](https://join.slack.com/t/getodk/shared_invite/zt-e68gf6xi-zhXbQ7gDRvMU6tRCQx1Jjg) is an invitation link that will hopefully work for you.
