### ISSUE TITLE
Metadata XForms examples use confusing namespace prefix

### ISSUE THREAD

**Issue by MartijnR** [getodk/docs#1239]
The namespaces used in the documentation examples at https://docs.getodk.org/openrosa-metadata/ are correct.

However, the namespace prefix used may be a little confusing (it was to me), because we're using `xmlns:jr="http://openrosa.org/xforms"` in the docs as opposed to `xmlns:orx="http://openrosa.org/xforms"` as we do in the [XForms spec](https://getodk.github.io/xforms-spec/#metadata). Moreover, we use the `jr` prefix for another namespace in the XForms spec, which is the real source of confusion.

I imagine, nobody cares much about this ;), but if desired, I can create a PR to reduce potential for confusion.

**Comment by lognaturel** [comment]
Wow, that is totally confusing! A good reminder that prefixes are arbitrary, I guess? But it does seem like a good change to me. 🙏
