### ISSUE TITLE
ODK Central custom db requires SSL - add config hint

### ISSUE THREAD

**Issue by florianm** [getodk/docs#1250]
### Problem
Using an external postgres db that requires SSL requires an additional config setting.

### Solution
https://github.com/getodk/central/issues/96

### Suggestion
Add solution to docs, e.g. expand step 4 of "Using a custom database server" at 
<https://github.com/getodk/docs/blob/master/odk1-src/central-install-digital-ocean.rst>

```
    "database": {
      "host": "my-db-host",
      "user": "my-db-user",
      "password": "my-db-password",
      "database": "my-db-table",
      "ssl": {"rejectUnauthorized": false}
    },
...
```

Minor: ` "database": "my-db-table",` is misleading as we want a database name, not a table within a schema within a database.

**Comment by lognaturel** [comment]
The issue turned out not to be about using a db with SSL but using a db with SSL and a self-signed cert. There's some discussion about how to provide some help around this in #1251.

**Comment by lognaturel** [comment]
This should now be addressed by the new database configuration docs.
