### ISSUE TITLE
Limited explanation when installing ODK Aggregate on Google Cloud

### ISSUE THREAD

**Issue by joesegal** [getodk/docs#1252]
When going through the documentation, it tells me how to setup the Google Cloud VM but doesn't explain how to install the actual ODK Aggregate on the VM. How is this done? Googling just bringing me info on the Google App Client. 

Thanks 
Joe

**Comment by yanokwa** [comment]
Step 10 at https://docs.getodk.org/aggregate-aws/#create-an-ec2-machine installs the software.
