### ISSUE TITLE
Improve the form styling section

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/docs#1315]
Improve the [form styling section](https://docs.getodk.org/form-styling/) and add info about centering text so that it's clear for our users.
See: https://forum.getodk.org/t/how-to-align-text-at-the-center/32227/3

**Comment by danbjoseph** [comment]
I was just about to come open an issue about this 😄 

The docs explicitly say: 
> These two attributes, `color` and `font-family`, are the only style attributes supported in Collect.

And `text-align` isn't mentioned in this page that's linked in the docs: 
> [The list of HTML tags currently supported in Collect.](https://www.grokkingandroid.com/android-quick-tip-formatting-text-with-html-fromhtml)
