### ISSUE TITLE
Update documentation for Collect projects and first launch (v2021.2)

### ISSUE THREAD

**Issue by lognaturel** [getodk/docs#1365]
- [x] Project name/icon/color can be configured from admin settings
- [x] Revise collect-settings
- [x] Demo project can be reconfigured or deleted
- [x] App version is at the bottom of the screen
- [x] First launch screen appears when there are no projects
- [x] QR code can be scanned or imported from image (useful when all staff are remote)
- [x] Icon and color for the current project are at top right and tapping it makes it possible to configure the current project or switch projects
- [x] App bar title is the project name
- [x] QR code has new `projects` object with new keys [here](https://github.com/getodk/collect/pull/4607/files#diff-e07bc4a275dc23c5fc4f81390c4498debea636dbc1d9c9158861d45ecf78048e)
- [x] Users are prompted to confirm when they enter in project connection details that match existing project(s) (getodk/collect#4697)

**Comment by seadowg** [comment]
Looking through the docs there is **A LOT** that needs to be revised. @lognaturel's list here is a good way to check that we've covered everything, but my process here is just to run throught the Collect docs in order and try and update/change things for projects.

**Comment by lognaturel** [comment]
I'm working on the last few items here.
