### ISSUE TITLE
Collect does not actually support `ACTION_PICK` for instances

### ISSUE THREAD

**Issue by seadowg** [getodk/docs#1375]
From https://docs.getodk.org/launch-collect-from-app/#getting-the-uri-of-a-form-or-instance-chosen-by-the-user. The title suggests that you can get "the URI of a form or instance chosen by the user" but this is only possible for forms (which luckily is what the code samples demonstrate).

**Comment by lognaturel** [comment]
This probably explains why builders of integrations used direct activity access instead of actions. We've decided to actually add the support with getodk/collect#4708
