### ISSUE TITLE
regex() is capitalized

### ISSUE THREAD

**Issue by matthew-white** [getodk/docs#1378]
Filing an issue related to this forum post: https://forum.getodk.org/t/field-not-validating-with-regex-with-correct-data/34573. It looks like `regex()` is capitalized in two places at https://docs.getodk.org/form-regex/ and that capitalization makes a difference.

**Comment by truthfool** [comment]
Hey @matthew-white thanks for raising the issue.
Pointing out the link : https://docs.getodk.org/form-regex/
In the example section of code :
`
<bind constraint="Regex(.,'^[a-zA-Z]{0,6}$')" jr:constraintMsg="Input can have a maximum of 6 alphabetic characters." nodeset="/regex_ex/ex" type="string"/>

<input ref="/regex_ex/ex">
   <label>Enter example</label>
 </input>
`
