### ISSUE TITLE
Update glossary items

### ISSUE THREAD

**Issue by seadowg** [getodk/docs#1391]
After running through the [glossary](https://docs.getodk.org/glossary/) with @eyelidlessness, we discovered it's in need of some updates:

- [x] No mention of Aggregate being deprecated
- [x] No mention of Central
- [x] "question label" and "question text" stacking is confusing, probably fine to give them their own descriptions

**Comment by grzesiek2010** [comment]
> No mention of Aggregate being deprecated

It's already been added.

> No mention of Central

It's already been added.

> "question label" and "question text" stacking is confusing, probably fine to give them their own descriptions

Those are just different names of the same element so I think it would be more confusing to have two descriptions that would indicate that they differ soemhow.
