### ISSUE TITLE
Document options for custom database server

### ISSUE THREAD

**Issue by matthew-white** [getodk/docs#1403]
https://docs.getodk.org/central-install-digital-ocean/#using-a-custom-database-server lists four configuration options for using a custom database server with ODK Central: `host`, `user`, `password`, and `database`. However, as of getodk/central-backend#394 (released with Central v1.3), the options `port` and `ssl` are also allowed. The only allowed value for `ssl` is `true`. Note that specifying `true` for `ssl` will automatically specify `false` for the SSL option `rejectUnauthorized`.

**Comment by lognaturel** [comment]
We now document `ssl` but not `port`. We'll add port if it's requested.
