### ISSUE TITLE
Link to download "Contributing to ODK Docs" documentation as PDF fails

### ISSUE THREAD

**Issue by jennifermklein** [getodk/docs#1417]
At the bottom of https://docs.getodk.org/contributing/, there is a link to "Download this documentation as a PDF." When the link is clicked, no file is downloaded.

**Comment by lognaturel** [comment]
Hi @jennifermklein!! Welcome!

I poked around a bit and I think the pdf download only works from the landing page and not from any topic pages. I think the next step is looking at the url from the main page vs topic page and see how they differ.
