### ISSUE TITLE
The odk-cmd doesn't work

### ISSUE THREAD

**Issue by jniles** [getodk/docs#1421]
The following does not work:

```bash
docker-compose exec service odk-cmd --email YOUREMAIL@ADDRESSHERE.com user-create
```
However, this works:

```bash
docker-compose exec service odk-cmd user-create -u YOUREMAIL@ADDRESSHERE.com
```

I'm not sure if this is a bug in the software or the documentation.

**Comment by matthew-white** [comment]
Hi @jniles, nice to see you! The first command you mention is similar to the one listed in the [docs](https://docs.getodk.org/central-command-line/#creating-a-web-user-by-command-line), so we want to make sure that that's working. I tried running that command on a server, but I didn't encounter an error. What version of ODK Central are you running, and what version of `docker-compose`? It'd also be helpful to hear more about went wrong when you ran the first command. Did you see an error message?

**Comment by jniles** [comment]
Hi @matthew-white ,

Sorry for not getting back to you.  This was a fresh install on digital ocean, and no error output was emitted, just a silent failure.

I will try to spin up a new droplet from the marketplace this week and see if the issue persists.
