### ISSUE TITLE
Attaching a file in image widgets might produce a file bigger than the original one

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/docs#1435]
#### Software and hardware versions 
Collect all versions

#### Problem description
Attaching a file in image widgets that was saved with lower quality than 80 (that we use in ODK Collect) when scaling down is used might cause producing a file that is not necessarily smaller than the original one (or it is even a bit bigger).

This is going to take place only if:
- a user attaches a file (not takes it via camera app)
- the file is a jpeg
- scaling down is enabled
- the attached image was saved with quality lower than 80

taking all of that into account it is going to be a very rare case.

#### Other information 
Ideally we should read quality from a file and use it if it's lower than 80 (that we use in our app). The problem is that there is no easy way to read that value.

**Comment by lognaturel** [comment]
Let's briefly mention this as an edge case. It might affect the workflow a form creator chooses. For example, this could convince them to do image capture within Collect rather than with an external app.
