### ISSUE TITLE
regex(.,'p{L}+') and regex(., 'p{L}') in constraints in xlsx form causes error message in ODK Collect app

### ISSUE THREAD

**Issue by dbemke** [getodk/docs#1477]
I recreated the example of a form with regex(.,'p{L}+') and  regex(., 'p{L}')  in constraints presented in https://docs.getodk.org/form-logic/#validating-and-restricting-responses
and saved it in xlsx file. 
![regexform](https://user-images.githubusercontent.com/56479916/175333857-24a1d470-1fb9-4e0e-8e6a-a3df1f23569f.png)
After submitting an answer in the form in ODK Collect error appears
![regexindocs](https://user-images.githubusercontent.com/56479916/175333789-a7215b4b-b74b-4482-bb35-dc0d0358dcee.jpg)

.

**Comment by lognaturel** [comment]
Thanks, good catch! The issue is that there's a `\` missing. The expressions should be `regex(.,'\p{L}+')` and `regex(., '\p{L}')`.
