### ISSUE TITLE
Disabling or customizing Sentry: mention organization subdomain

### ISSUE THREAD

**Issue by lognaturel** [getodk/docs#1501]
The section on [Disabling or Customizing Sentry](https://docs.getodk.org/central-install-digital-ocean/#disabling-or-customizing-sentry) needs to be updated to account for a new Sentry configuration, organization subdomain. That configuration was added in getodk/central#312 as part of v1.5.3.

**Comment by matthew-white** [comment]
I've split out part of this to #1503 so that this issue is just about updating the docs about the Sentry organization subdomain. I'd be happy to work on #1503 since I wrote those instructions.
