### ISSUE TITLE
Update Sentry docs for Central v2022.3

### ISSUE THREAD

**Issue by lognaturel** [getodk/docs#1502]
Update the section on [Disabling or Customizing Sentry](https://docs.getodk.org/central-install-digital-ocean/#disabling-or-customizing-sentry) to describe how to disable or customize CSP reporting.

@alxndrsn

**Comment by yanokwa** [comment]
Closed by #1504, #1502

**Comment by lognaturel** [comment]
This hasn't been released yet but I think it's not a big deal in this case since the CSP reporting URL that's mentioned just won't be there. @alxndrsn it would be helpful in the future to either have a note saying you considered that and decided it didn't matter or tagging the PR as `future release` so it doesn't get merged right away.
