### ISSUE TITLE
Document using custom camera apps in Collect

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/docs#1652]
Document using custom camera apps in Collect. See: https://github.com/getodk/collect/pull/5738 and https://github.com/XLSForm/pyxform/issues/651

**Comment by lognaturel** [comment]
Some special things to note:
The app with the provided package name must be installed on the device. If it's not available, there will be a toast shown and it will not be possible to take a picture.

By default, it's also possible to select a picture from the device. Use the `new` appearance to prevent this.

Collect will request a picture but some camera apps may still allow users to take video. That will fail silently.
