### ISSUE TITLE
Changing "Widgets" to "Question type" in the All Widgets form

### ISSUE THREAD

**Issue by alyblenkin** [getodk/docs#1740]
Updating the language in the demo form, so we always refer to 'widgets' as 'question types' to make it more user-friendly. 

Using 'question type' instead of 'widgets' will be a major change for docs and in our communications (e.g. social media or the forum).

**Comment by grzesiek2010** [comment]
I've just changed all appearances of `widgets` to `questions` in the form. @lognaturel I've noticed that you have started renaming questions by removing the old widgets suffix at all, eg. String widgets -> String. Is that what we should do in the entire form?

**Comment by lognaturel** [comment]
There were some inconsistency in the issue description -- "widget" should become "question type", not "question"

Yes, I think we should just remove the suffix for section and question names. I got pulled away part way through, sorry about that! Let me know when it's done and I'll push it to the demo server.

**Comment by alyblenkin** [comment]
> There were some inconsistency in the issue description -- "widget" should become "question type", not "question"

Yes, that was my bad! I meant to write 'question type'!

**Comment by grzesiek2010** [comment]
> Let me know when it's done and I'll push it to the demo server.

It should be ready.

**Comment by lognaturel** [comment]
Thanks so much, @grzesiek2010! It's up on the demo server. I used a separate form id and marked the original All Widgets form as 'closing'. That means some people may end up with both forms downloaded on their devices and I think that's ok.
