### ISSUE TITLE
Entities tutorial : error with current() fonction

### ISSUE THREAD

**Issue by tomgachet** [getodk/docs#1772]
Hi!
In [this section](https://docs.getodk.org/tutorial-community-reporting/#update-a-problem-s-status)  of the entities tutorial, the _current()_ fonction crashes ODK Collect.
The choice filter _`status != 'addressed' or name = current()`_ should be `status != 'addressed' or name = current()/.`

**Comment by lognaturel** [comment]
Oh dear, thanks so much for catching that! We really need to address this in JavaRosa: https://github.com/getodk/javarosa/issues/510
