### ISSUE TITLE
SUGGESTION Add working examples for ODK Aggregate API to docs

### ISSUE THREAD

**Issue by florianm** [getodk/docs#352]
## Description
Working with the ODK Aggregate API is really useful as it helps to automate recurring tasks.
Some working examples of the most used API tasks would be great to have in the docs.

E.g., I'd love to see working examples in Python and R for the following tasks:

* List all forms (`/xformsList`) to show at least name and downloadUrl in tabular format.
* For one formID, list all form submissions (`/view/submissionList`). Handle pagination (GET parameter `limit`, opaque resumption cursor) recursively and merge chunks into one list of submission IDs.
* For one formID and one submissionID, retrieve the submission and parse to a sane data structure (`/view/downloadSubmission?`). Possibly extract the common fields into separate columns (submission ID etc), parse media to a "name:url" dict (save as one extra column) and parse data into a dict column.

Examples in Python and R would be great. API wrapper packages (Python / R) would be even greater and a possible follow-up to working examples. A shared headache is to parse the XML from the ODK API to Python dicts or R tibbles, respectively.

Further wish list - not sure whether API endpoints exist:

* create new ODK-A users, (re-)set passwords
* import / export list of users

Answering my own question: 

* Add https://github.com/opendatakit/opendatakit/wiki/ODK-2.0-Synchronization-API-(RESTful) to the docs

Edit May 2020. My legacy code reading ODK Aggregate's OpenRosa API is [here](https://github.com/dbca-wa/wastd/blob/master/wastd/observations/utils.py#L5398).

The new ODK Central offers a well-documented API [with working examples](https://odkcentral.docs.apiary.io/). [ruODK](https://dbca-wa.github.io/ruODK/) is an ODK Central API client in R.

**Comment by aivernermine** [comment]
Hi ... Thanks for providing some light on the APIs for ODK-A. Do you have any idea on the format of the cursor for resuming a download on the ODK API? That is here /view/submissionList?cursor=???...

I have been trying to look at how briefcase passes this cursor to the API but my JAVA is none existent and I am not getting anywhere. 

I know how to get the last resumptionCursor but which part of it do I pass back to ODK-A. How do I parse it? And does it need to be Base64? Here is what I have tried with no success:-

cursor=2020-05-06T08:13:36.147+0000uuid:4e4e51f9-0a68-4abe-a9bb-428274949fbdtrue
cursor=uuid:4e4e51f9-0a68-4abe-a9bb-428274949fbd
cursor= PHJlc3VtcHRpb25DdXJzb3I+CjxjdXJzb3IgeG1sbnM9Imh0dHA6Ly93d3cub3BlbmRhdGFraXQu
b3JnL2N1cnNvciI+PGF0dHJpYnV0ZU5hbWU+X0xBU1RfVVBEQVRFX0RBVEU8L2F0dHJpYnV0ZU5h
bWU+PGF0dHJpYnV0ZVZhbHVlPjIwMjAtMDUtMDZUMDg6MTM6MzYuMTQ3KzAwMDA8L2F0dHJpYnV0
ZVZhbHVlPjx1cmlMYXN0UmV0dXJuZWRWYWx1ZT51dWlkOjRlNGU1MWY5LTBhNjgtNGFiZS1hOWJi
LTQyODI3NDk0OWZiZDwvdXJpTGFzdFJldHVybmVkVmFsdWU+PGlzRm9yd2FyZEN1cnNvcj50cnVl
PC9pc0ZvcndhcmRDdXJzb3I+PC9jdXJzb3I+CjwvcmVzdW1wdGlvbkN1cnNvcj4=

Please help... there seems to be no documentation out there on this. 

I have tried some

**Comment by lognaturel** [comment]
I want to highlight an update from @florianm! 

> Edit May 2020. My legacy code reading ODK Aggregate's OpenRosa API is [here](https://github.com/dbca-wa/wastd/blob/master/wastd/observations/utils.py#L5398).

> The new ODK Central offers a well-documented API [with working examples](https://odkcentral.docs.apiary.io/). [ruODK](https://dbca-wa.github.io/ruODK/) is an ODK Central API client in R.

Aggregate is no longer actively developed so I think we can close this issue. Central is its replacement.

@aivernermine I know you deleted your follow-up so hopefully that means you have been able to make progress. In general, support questions are going to get more attention [on the forum](https://forum.getodk.org/).
