### ISSUE TITLE
Form design for Collect hierarchy view: add inner group to control repeat titles

### ISSUE THREAD

**Issue by lognaturel** [getodk/docs#376]
As of Collect v1.12.0 (to be released ~12/17), when a group is nested directly in a repeat the name of that group is used in the hierarchy view as the repeat title. Where should this be documented? Probably in both the XForms and XLSForm specifications. Somewhere in form tips here? Collect documentation? This is optional behavior that clients may choose to ignore or not.

@hooverlunch @grzesiek2010 you may have some ideas!

**Comment by hooverlunch** [comment]
I have not yet had time to review the new Collect docs per @yanokwa's request, but I am still hoping to find time.

But based on an initial look, I don't see anything about repeat groups in the ODK Collect docs. There is stuff about widgets, but not groups (except field lists) or repeats. Am I missing it?

If I'm not, is this an oversight? I get that the XForms spec is the definitive source for XML-y stuff, but as long as there are snippets for all the widgets in the Collect docs, seems like there should be snippets for groups too? 

Then this would be a natural place to describe the named repeat stuff, in addition to the XForms and XLSForms specs, which I agree it totally needs to be there too.

**Comment by adammichaelwood** [comment]
What is the "hierarchy view"?

**Comment by smoyth** [comment]
The jump screen?

See this thread: https://github.com/opendatakit/xforms-spec/issues/141
