### ISSUE TITLE
Aggregate limitation re: Queueing time refers to what?

### ISSUE THREAD

**Issue by adammichaelwood** [getodk/docs#421]
From aggregate-limitations.rst

> Spinning up of copies of the frontend will incur faster quota usage on AppEngine. For that reason, the Aggregate configuration here specifies a 14-second queuing time threshold before a new instance is spun up. Only if at least one request is queued for longer than 14 seconds will a new instance be spun up, and then that new instance will take about 30 seconds to become live. Leaving a 15-second processing interval. This is why ODK Collect tried twice before failing a submit.

This is unclear, and I am having trouble understand it enough to know how to fix it.

 > the Aggregate configuration here specifies a 14-second queuing time

What is the where specified by "here"? I've searched the docs, the forum, and CTRL-Fed the Aggregate installation pages, and I can't find a mention of it. Is it built in?

> This is why ODK Collect tried twice before failing a submit

When?

This sounds like a response to a specific support question in a particular case - but I can't find the source of this text in the forum.

**Comment by adammichaelwood** [comment]
@ankita240796 This was your PR. Any insights?

**Comment by adammichaelwood** [comment]
Oh... I found the original gh issue that mentioned it.

**Comment by adammichaelwood** [comment]
> the aggregate configuration *here*

This was [a link, which is now defunct](https://github.com/opendatakit/aggregate/blob/master/eclipse-default/WebContent/WEB-INF/appengine-web.xml).

**Comment by adammichaelwood** [comment]
The original list of four issues were originally written *to developers of ODK* in a conversation about how to optimize downloads and uploads between Briefcase and Aggregate. 

I'm wondering how relevant and helpful they are to users and implementers. Serializing connection to Aggregate seems like something you would need/care to do in a deployment to a lot of devices. Items three is less clear to me, unless it just means "Don't connect too many devices for download of forms all at once.") The fourth item, the one quoted at the top of this thread, is very opaque.

**Comment by yanokwa** [comment]
Closing because Aggregate is no longer being updated.
