### ISSUE TITLE
Add Aggregate publishing info

### ISSUE THREAD

**Issue by adammichaelwood** [getodk/docs#443]
Details from here:  
https://github.com/opendatakit/opendatakit/wiki/Aggregate-Publishers-Implementation-Details

should be used to improve the Publishing section of aggregate-data-access:  
http://docs.opendatakit.org/aggregate-data-access/#publishing

It *might* make sense to pull Publishing into its own doc if adding this info makes the whole doc too large.

**Comment by yanokwa** [comment]
Closing because Aggregate is no longer being updated.
