### ISSUE TITLE
Review statements about Aggregate/App Engine pricing

### ISSUE THREAD

**Issue by adammichaelwood** [getodk/docs#525]
In `aggregate-deployment-planning`, [some statements are made about App Engine pricing](http://docs.opendatakit.org/aggregate-deployment-planning/#app-engine-is-usually-sufficient), including mention of weekly billing, a weekly minimum rate, and the typical cost of the ODK Aggregate demo server.

It [seems that this information is not accurate](https://cloud.google.com/appengine/pricing) any longer --- there's no mention in current pricing about weekly billing or weekly minimums. (I don't know what the cost for the Demo Server is.)

The general message of this section is: Google App Engine is usually a good idea, sufficient to most needs, and cost effective. I assume this is still true.

We could eliminate specific pricing mentions altogether. We could update with current info. We could keep the info that is there, but make it clear it is historical. It would be nice if we had any other cost-comparison information. (Does some exist? Should we do a survey and generate some?)

**Comment by adammichaelwood** [comment]
Note --- I will probably comment out the pricing specific info in an upcoming editing PR. But we should still circle back on a thoughtful decision about providing this info.

**Comment by yanokwa** [comment]
Closing because Aggregate (especially on App Engine) is no longer being updated.
