### ISSUE TITLE
Add details and limitations to using Google Drive with Collect

### ISSUE THREAD

**Issue by adammichaelwood** [getodk/docs#619]
From @lognaturel, on #164:

> Some information that should be included is that the Google Drive integration does not support repeats and can handle a maximum of 255 questions because of a Google Sheet limitation.

> In Collect 1.14.0+, Google Drive integration will support repeats.
> The 255 questions limit still applies.

We need to make it more clear that you cannot host an XLSForm as a Google Sheet --- even if you build your XLSXForm in Google Sheet, you still have to DL as .xlsx and convert to XForm. Then you host the XML document in your Google Drive. Then submissions data are stored in a Google Sheet.

This should be added to `collect-connect-google` (and possibly referenced in `collect-forms`).

**Comment by grzesiek2010** [comment]
We can close as GD integration was removed from Collect.
