### ISSUE TITLE
Published Data will stop if you move the target file on Google Drive

### ISSUE THREAD

**Issue by Ken14** [getodk/docs#639]
The documentation should note that when you publish data in a continuous stream, if on google drive you move the file to a folder while active, ODK Aggregate will stop/pause publishing because the security profile of the document has changed.

Currently Aggregate publishes to the top level of the google drive of the target account.  If the data manager wants the file(s) in a different folder, google changes the security of the file(s) because the folder is a different security domain from the top level.  

ODK shows the data transfer as paused.  Google Console for the project shows the security errors.

**Comment by yanokwa** [comment]
Aggregate has reached end-of-life so we aren't updating any docs related to it.
