### ISSUE TITLE
Missing content about multi-host and load-balancing?

### ISSUE THREAD

**Issue by yanokwa** [getodk/docs#668]
https://opendatakit.org/use/aggregate/tomcat-install/ has some language about multi-host and load-balancing considerations. I don't see that in the docs. @adammichaelwood do you know where this went?

**Comment by adammichaelwood** [comment]
I don't know where that went. 
(I started poking around old PRs to find out, but I guess it really doesn't matter at this point.)

Probably should be added to the "Considerations before you begin" section.

**Comment by yanokwa** [comment]
Stuff like this makes nervous. The website is going away soon and it'd be good to sanity check all the docs to make sure we aren't missing anything.

**Comment by adammichaelwood** [comment]
Yeah. We should do comb through. Also, archive the content somewhere so it can't be completely lost forever.

**Comment by yanokwa** [comment]
Aggregate has reached end-of-life so we aren't updating any docs related to it.
