### ISSUE TITLE
warning about field names not starting with digits

### ISSUE THREAD

**Issue by adammichaelwood** [getodk/docs#677]
From the old gotchas document:
https://opendatakit.org/help/form-design/workarounds/

-----

### field names starting with digits fail validation

Field names should not start with digits. I.e., the field name 2014crops is not allowed, but crops2014 is. This is requirement from the XML specification:

The element tags are case-sensitive; the beginning and end tags must match exactly. Tag names cannot contain any of the characters !"#$%&'()*+,/;<=>?@[\]^`{|}~, nor a space character, and cannot start with -, ., or a numeric digit.

Some of our tools may vary in how strict they are in applying this rule.

-----

Not sure where this should go. (I'm not a big fan of "gotcha" pages.

I was thinking about a "Form Widget Anatomy" doc/section,
and this might be good there.

**Comment by lognaturel** [comment]
We now have some detail about naming fields at https://docs.getodk.org/xlsform/#the-survey-sheet
