### ISSUE TITLE
Display only newest form versions in Collect

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/docs#710]
On the Collect's side, we are going to hide old form versions. I mean if a user has a few forms with the same `formId` and `version number` only the newest one should be displayed. By `the newest one`, I mean
the form with the highest `version number` or the newest one if all `version numbers` are the same.
More info: https://github.com/opendatakit/collect/issues/1694

**Comment by lognaturel** [comment]
https://docs.opendatakit.org/form-update/ is where the update needs to go.
