### ISSUE TITLE
Select custom offline map from settings

### ISSUE THREAD

**Issue by lognaturel** [getodk/docs#750]
https://docs.opendatakit.org/collect-offline-maps/ describes how to use custom map tiles. As of https://github.com/opendatakit/collect/pull/1649 (to be released in Collect v1.16.0), custom offline tiles can be selected from settings.

This should be added to https://docs.opendatakit.org/collect-settings/ matching the structure of other setting and should link to https://docs.opendatakit.org/collect-offline-maps/.

**Comment by grzesiek2010** [comment]
It looks like it has been fixed in https://github.com/getodk/docs/pull/1080
