### ISSUE TITLE
Pull in docs to configure Aggregate's network access 

### ISSUE THREAD

**Issue by yanokwa** [getodk/docs#807]
https://web.archive.org/web/20170710014117/https://opendatakit.org/use/aggregate/tomcat-install#configure-for-network-access has some useful docs that we should pull in.

Related: #804

**Comment by lognaturel** [comment]
@yanokwa Do you have a recommendation for where this should go to make it a little easier for someone to help out?

**Comment by yanokwa** [comment]
I'd put it under Tips and Best Practices in a `aggregate-networking` document.

**Comment by yanokwa** [comment]
Closing because Aggregate is no longer being updated.
