### ISSUE TITLE
Narrative on how to use XPath / XForms functions when building forms

### ISSUE THREAD

**Issue by lognaturel** [getodk/docs#85]
I think the functions themselves should probably live in the [XForms spec](https://github.com/opendatakit/xforms-spec) but it would be helpful to have a description of where they can be used and a series of examples. I think the section on operators [here](https://opendatakit.org/help/form-design/binding/) can be split up into beefing up what exists in the spec and some examples that would be in the form design docs.

[This grid](http://xlsform.org/ref-table/) specifies what is implemented in which client. I think a link to this should show up somewhere in this narrative.

This issue was inspired by [this post](https://forum.opendatakit.org/t/counting-the-number-of-options-chosen-on-a-select-multiple-variable/9485).

**Comment by adammichaelwood** [comment]
@lognaturel 

I would love to hear an opinion on what is still needed on this issue after the functions pull request
