### ISSUE TITLE
Convert "XLSX Converter->Built In Functionality" Docs Updates

### ISSUE THREAD

**Issue by jbeorse** [getodk/docs#862]
In [this forum thread](https://forum.opendatakit.org/t/community-contributions-to-upcoming-odk-2-0-documentation-refresh/11324/9?u=jeff_beorse), ODK 2 users have contributed updates to the documentation. To resolve this issue, the changes outlined in [Built in Functionality 9.1.18 CGK.docx](https://github.com/opendatakit/docs/files/2413711/Built.in.Functionality.9.1.18.CGK.docx) should be implemented on the [corresponding page](https://docs.opendatakit.org/odk2/xlsx-converter-reference/#built-in-functionality).

This issue involves no new copy writing, just implementing existing copy changes in the proper Sphinx syntax.

**Comment by charanjit-singh** [comment]
@opendatakit-bot claim

**Comment by b18050** [comment]
claim the same issue if it is still pen.

**Comment by jchenj** [comment]
@opendatakit-bot claim if available, please

**Comment by jchenj** [comment]
Still working on it! :)
