### ISSUE TITLE
Minor edits to aggregate-upgrade docs

### ISSUE THREAD

**Issue by jcdavids** [getodk/docs#906]
Here are some suggested edits to the aggregate-update docs regarding Determining your Aggregate version:

***

5. Click on any of the returned logs and then click on 'Expand all' to show the entire log.

![expand-all](https://user-images.githubusercontent.com/22315404/47857434-e42be300-dde9-11e8-9353-7a20a42e9e32.png)

6. Using your web browsers' search function (e.g. Ctrl + F) search for 'afterPropertiesSet' to find its first instance in the expanded log which is followed by the version of Aggregate. It will be similar to the following format:

![find-version2](https://user-images.githubusercontent.com/22315404/47857449-ed1cb480-dde9-11e8-9b83-5fc7d450e3ee.png)

***

Also for General steps for upgrading, I would suggest the following edit to number 5:

5. Download the latest production release (e.g. 1.6.latest) of the next ODK Aggregate version and upgrade to that version.  

Number 7 could be edited to:

7. Repeat steps 4-7 until you have upgraded to the current version.  For example, if you are currently running v1.4.15, the upgrade path would include: v1.5.latest, v1.6.latest, etc. until the latest production release is installed.

**Comment by yanokwa** [comment]
Aggregate has reached end-of-life so we aren't updating any docs related to it.
